const actionTypes = {
LOGOUT: "LOGOUT",
GET_USER: "GET_USER",
AUTHENTICATION: "AUTHENTICATION",
SET_USER: "SET_USER",
SET_MATCHES: "SET_MATCHES",
SET_REQUESTS: 'SET_REQUESTS'
};

export default actionTypes;